// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvvduznreughixeyutyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2dmR1em5yZXVnaGl4ZXl1dHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODM2MzQsImV4cCI6MjA2ODc1OTYzNH0.O5tqH28ULuL-Gp3haasfLyoSZRg2c5k1cVItVYa-SUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});